# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81d1fd6ac63d72aeaa0229e90b7e60afa3d12ec036bddbe9bcb2e05d7d369a2f7e2930724ae17f3401aa0bd1ec8a27d413ddb478ef67d0b9f3c759fec1916855

test:
  secret_key_base: 3e019469160fbb7cf34aea45638d1533831e56c2c6fbfc3cc918115f9611001312fa88dd0b772261070b5b15bf3d3bd3033ff45432efba3bec8960dea76e9ce1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
